<?php
/**
 * Ten products/services for Products & Services section.
 * Each has its own page; slugs are used in URLs and cookies.
 */
return [
    [
        'id' => 'bridal-makeup',
        'slug' => 'bridal-makeup',
        'name' => 'Bridal Makeup',
        'category' => 'Makeup',
        'price' => 15000,
        'duration' => '3 hours',
        'description' => 'Our signature bridal makeup brings together traditional elegance and modern techniques. We create a look that photographs beautifully and lasts through the entire celebration. Includes trial session, premium products, and optional touch-ups.',
        'image' => 'https://images.unsplash.com/photo-1742891602815-fa2a195f0ab3?auto=format&fit=crop&w=800&q=82',
    ],
    [
        'id' => 'party-makeup',
        'slug' => 'party-makeup',
        'name' => 'Party & Event Makeup',
        'category' => 'Makeup',
        'price' => 2500,
        'duration' => '1 hour',
        'description' => 'Glamorous party looks tailored to your outfit and the occasion. From sangeet to reception, we ensure you look camera-ready and feel confident all night. Includes false lashes and long-wear setting.',
        'image' => 'https://images.unsplash.com/photo-1616513779308-3691c6901813?auto=format&fit=crop&w=800&q=82',
    ],
    [
        'id' => 'engagement-makeup',
        'slug' => 'engagement-makeup',
        'name' => 'Engagement Makeup',
        'category' => 'Makeup',
        'price' => 8000,
        'duration' => '2 hours',
        'description' => 'Soft, romantic looks perfect for your engagement. We highlight your best features with a dewy, photo-friendly finish. Ideal for pre-wedding events and portrait sessions.',
        'image' => 'https://images.unsplash.com/photo-1770747874505-67d0a43379d5?auto=format&fit=crop&w=800&q=82',
    ],
    [
        'id' => 'hair-spa',
        'slug' => 'hair-spa',
        'name' => 'Hair Spa',
        'category' => 'Hair',
        'price' => 1200,
        'duration' => '1 hour',
        'description' => 'A relaxing hair spa treatment that nourishes from root to tip. Restores shine, reduces frizz, and strengthens hair. Perfect before big events or as regular maintenance.',
        'image' => 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=82',
    ],
    [
        'id' => 'clean-up-facial',
        'slug' => 'clean-up-facial',
        'name' => 'Clean Up & Basic Facial',
        'category' => 'Skin',
        'price' => 500,
        'duration' => '30 mins',
        'description' => 'Deep cleansing, exfoliation, and a gentle facial massage to refresh your skin. Ideal for regular upkeep and a healthy glow. Suitable for all skin types.',
        'image' => 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=800&q=82',
    ],
    [
        'id' => 'fruit-facial',
        'slug' => 'fruit-facial',
        'name' => 'Fruit Facial',
        'category' => 'Skin',
        'price' => 800,
        'duration' => '45 mins',
        'description' => 'Natural fruit extracts and vitamins to brighten and rejuvenate your skin. Gentle, refreshing, and ideal for a pre-event glow or weekly self-care.',
        'image' => 'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?auto=format&fit=crop&w=800&q=82',
    ],
    [
        'id' => 'bridal-mehndi',
        'slug' => 'bridal-mehndi',
        'name' => 'Bridal Mehndi',
        'category' => 'Mehndi',
        'price' => 5000,
        'duration' => '3 hours',
        'description' => 'Intricate bridal mehndi designs—full hands and feet—with rich, long-lasting stain. Traditional and contemporary patterns to match your wedding theme.',
        'image' => 'https://images.unsplash.com/photo-1673413606600-7396eb476374?auto=format&fit=crop&w=800&q=82',
    ],
    [
        'id' => 'saree-draping',
        'slug' => 'saree-draping',
        'name' => 'Saree Draping & Styling',
        'category' => 'Styling',
        'price' => 300,
        'duration' => '20 mins',
        'description' => 'Professional saree draping and pleating for events. We help you get the perfect fall and pallu style, whether traditional or modern drape.',
        'image' => 'https://images.unsplash.com/photo-1641699862936-be9f49b1c38d?auto=format&fit=crop&w=800&q=82',
    ],
    [
        'id' => 'pre-bridal-package',
        'slug' => 'pre-bridal-package',
        'name' => 'Pre-Bridal Package (Premium)',
        'category' => 'Bridal',
        'price' => 10000,
        'duration' => '6 hours',
        'description' => 'Complete pre-bridal package: skin prep, facial, body polish, hair treatment, trial makeup, and styling advice. Designed so you look and feel your best on the big day.',
        'image' => 'https://images.unsplash.com/photo-1762708594532-46345d574457?auto=format&fit=crop&w=800&q=82',
    ],
    [
        'id' => 'nail-art',
        'slug' => 'nail-art',
        'name' => 'Nail Art & Gel Polish',
        'category' => 'Nails',
        'price' => 800,
        'duration' => '45 mins',
        'description' => 'Trendy nail art and long-lasting gel polish. From subtle elegance to bold designs, we match your outfit and occasion. Includes nail shaping and cuticle care.',
        'image' => 'https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=800&q=82',
    ],
];
